import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { useLanguage } from '@/i18n/LanguageContext';
import { useBeforeAfterCases, useSitePage } from '@/hooks/useCmsContent';
import { useSEO } from '@/hooks/useSEO';
import { WhatsAppButton } from '@/components/dental/WhatsAppButton';
import { ChevronLeft, ChevronRight, X } from 'lucide-react';
import { clinicalCases } from '@/data/clinicalCases';

type DisplayCase = { id: string; title: string; description: string; before: string; after?: string; beforeAlt: string; afterAlt?: string };

export default function BeforeAfterPage() {
  const { t, lang } = useLanguage();
  const { data: dbCases } = useBeforeAfterCases();
  const { data: page } = useSitePage('before-after');
  const [lightbox, setLightbox] = useState<number | null>(null);

  const ui = {
    en: { seoTitle: 'Dental Before and After Results | Temelci Dental', seoDescription: 'View documented dental transformations including veneers, implants, crowns and smile makeovers.', consent: 'Real patients · Published with consent', documented: 'documented transformations', ready: 'Ready to start your transformation?', emptyTitle: 'New clinical cases are being prepared', emptyText: 'Only cases with documented patient consent are published here. Contact our team to discuss results relevant to your treatment.', before: 'Before', after: 'After', clinical: 'Clinical case', view: 'View case', result: 'View result', caseTitle: 'Patient transformation', close: 'Close', previous: 'Previous', next: 'Next', final: 'Send us your smile photos for a free personalised assessment.' },
    de: { seoTitle: 'Zahnbehandlung Vorher und Nachher | Temelci Dental', seoDescription: 'Sehen Sie dokumentierte Zahnbehandlungen mit Veneers, Implantaten, Kronen und Smile Makeovers.', consent: 'Echte Patienten · Mit Einwilligung veröffentlicht', documented: 'dokumentierte Behandlungen', ready: 'Bereit für Ihre persönliche Beratung?', emptyTitle: 'Neue klinische Fälle werden vorbereitet', emptyText: 'Wir veröffentlichen nur Fälle mit dokumentierter Einwilligung. Sprechen Sie mit unserem Team über Ergebnisse, die für Ihre Behandlung relevant sind.', before: 'Vorher', after: 'Nachher', clinical: 'Klinischer Fall', view: 'Fall ansehen', result: 'Ergebnis ansehen', caseTitle: 'Patientenbehandlung', close: 'Schließen', previous: 'Zurück', next: 'Weiter', final: 'Senden Sie uns Ihre Lächelnfotos für eine kostenlose persönliche Einschätzung.' },
    tr: { seoTitle: 'Diş Tedavisi Öncesi ve Sonrası | Temelci Dental', seoDescription: 'Veneer, implant, kron ve gülüş tasarımı dahil belgelenmiş diş tedavisi sonuçlarını inceleyin.', consent: 'Gerçek hastalar · Onayla yayımlandı', documented: 'belgelenmiş dönüşüm', ready: 'Kişisel değerlendirmenize başlamaya hazır mısınız?', emptyTitle: 'Yeni klinik vakalar hazırlanıyor', emptyText: 'Yalnızca belgelenmiş hasta onayı bulunan vakalar yayımlanır. Tedavinizle ilgili sonuçları görüşmek için ekibimizle iletişime geçin.', before: 'Önce', after: 'Sonra', clinical: 'Klinik vaka', view: 'Vakayı gör', result: 'Sonucu gör', caseTitle: 'Hasta dönüşümü', close: 'Kapat', previous: 'Önceki', next: 'Sonraki', final: 'Ücretsiz kişisel değerlendirme için gülüş fotoğraflarınızı gönderin.' },
    he: { seoTitle: 'לפני ואחרי טיפולי שיניים | Temelci Dental', seoDescription: 'צפו בתוצאות מתועדות של ציפויים, שתלים, כתרים ועיצוב חיוך.', consent: 'מטופלים אמיתיים · פורסם בהסכמה', documented: 'שינויים מתועדים', ready: 'מוכנים להתחיל הערכה אישית?', emptyTitle: 'מקרים קליניים חדשים בהכנה', emptyText: 'אנו מפרסמים רק מקרים עם הסכמה מתועדת. צרו קשר כדי לדון בתוצאות הרלוונטיות לטיפול שלכם.', before: 'לפני', after: 'אחרי', clinical: 'מקרה קליני', view: 'צפייה במקרה', result: 'צפייה בתוצאה', caseTitle: 'שינוי חיוך של מטופל', close: 'סגירה', previous: 'הקודם', next: 'הבא', final: 'שלחו תמונות חיוך לקבלת הערכה אישית ללא עלות.' },
    ru: { seoTitle: 'До и после лечения зубов | Temelci Dental', seoDescription: 'Посмотрите документированные результаты лечения винирами, имплантами, коронками и дизайна улыбки.', consent: 'Реальные пациенты · Опубликовано с согласия', documented: 'документированных результатов', ready: 'Готовы начать персональную консультацию?', emptyTitle: 'Новые клинические случаи готовятся', emptyText: 'Мы публикуем только случаи с документированным согласием пациента. Свяжитесь с нами, чтобы обсудить результаты, относящиеся к вашему лечению.', before: 'До', after: 'После', clinical: 'Клинический случай', view: 'Открыть случай', result: 'Посмотреть результат', caseTitle: 'Преображение пациента', close: 'Закрыть', previous: 'Назад', next: 'Вперёд', final: 'Отправьте фотографии улыбки для бесплатной персональной оценки.' },
  }[lang];

  useSEO({ title: lang === 'en' && page?.seo_title ? page.seo_title : ui.seoTitle, description: lang === 'en' && page?.seo_description ? page.seo_description : ui.seoDescription, canonical: `https://temelcidentist.com/${lang}/${t.beforeAfterSlug}`, ogImage: page?.og_image || undefined });

  const cmsCases: DisplayCase[] = (dbCases || []).map((item, index) => ({ id: item.id, title: lang === 'en' ? (item.title || ui.caseTitle) : `${ui.caseTitle} ${index + 1}`, description: lang === 'en' ? (item.description || '') : '', before: item.before_image, after: item.after_image, beforeAlt: `${ui.before}: ${ui.caseTitle}`, afterAlt: `${ui.after}: ${ui.caseTitle}` }));
  const staticCases: DisplayCase[] = clinicalCases.map((item, index) => ({ id: item.id, title: lang === 'en' ? item.title : `${ui.caseTitle} ${index + 1}`, description: lang === 'en' ? item.description : '', before: item.before_image, after: item.after_image, beforeAlt: `${ui.before}: ${ui.caseTitle}`, afterAlt: `${ui.after}: ${ui.caseTitle}` }));
  const cases = [...staticCases, ...cmsCases.filter(item => !staticCases.some(staticItem => staticItem.id === item.id))];

  const close = () => { setLightbox(null); document.body.style.overflow = ''; };
  const open = (index: number) => { setLightbox(index); document.body.style.overflow = 'hidden'; };
  const move = (offset: number) => setLightbox(current => current === null ? null : (current + offset + cases.length) % cases.length);

  return <>
    <section className="section-padding bg-secondary/30"><div className="container-dental text-center"><div className="inline-flex items-center gap-2 bg-primary/10 border border-primary/20 text-primary text-xs font-semibold px-4 py-2 rounded-full mb-4 uppercase tracking-wider">{ui.consent}</div><h1 className="heading-display mb-4">{lang === 'en' && page?.hero_title ? page.hero_title : t.beforeAfterTitle}</h1><p className="text-body max-w-2xl mx-auto">{lang === 'en' && page?.hero_description ? page.hero_description : t.beforeAfterSubtitle}</p>{cases.length > 0 && <p className="mt-5 text-sm text-muted-foreground"><strong className="text-primary">{cases.length}</strong> {ui.documented}</p>}</div></section>
    <section className="bg-primary py-5"><div className="container-dental px-4 flex flex-wrap items-center justify-center gap-4"><p className="text-primary-foreground font-medium text-sm">{ui.ready}</p><WhatsAppButton text={t.sendSmilePhotos} variant="hero" /></div></section>
    <section className="section-padding bg-background"><div className="container-dental">{cases.length === 0 ? <div className="rounded-2xl border bg-card p-10 text-center"><h2 className="font-display text-2xl font-semibold">{ui.emptyTitle}</h2><p className="text-muted-foreground mt-2 max-w-xl mx-auto">{ui.emptyText}</p></div> : <div className="ba-grid">{cases.map((item, index) => <motion.button type="button" key={item.id} className="ba-card text-left" initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-40px' }} transition={{ delay: (index % 4) * 0.06, duration: 0.4 }} onClick={() => open(index)}><div className="ba-img-wrap">{item.after ? <div className="grid grid-cols-2 h-full"><div className="relative"><img src={item.before} alt={item.beforeAlt} className="ba-img" loading="lazy" /><span className="absolute left-2 bottom-2 ba-badge ba-badge--before">{ui.before}</span></div><div className="relative"><img src={item.after} alt={item.afterAlt} className="ba-img" loading="lazy" /><span className="absolute right-2 bottom-2 ba-badge ba-badge--after">{ui.after}</span></div></div> : <div className="relative h-full bg-secondary/30"><img src={item.before} alt={item.beforeAlt} className="ba-img object-contain" loading="lazy" /><span className="absolute left-2 bottom-2 ba-badge ba-badge--after">{ui.clinical}</span></div>}<div className="ba-overlay"><span className="ba-zoom">{ui.view}</span></div></div><div className="ba-card-footer"><span className="ba-patient">{item.title}</span><span className="ba-cta-link">{ui.result} →</span></div></motion.button>)}</div>}</div></section>
    <AnimatePresence>{lightbox !== null && <motion.div className="ba-lightbox" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close}><button className="ba-lb-close" onClick={close} aria-label={ui.close}><X size={22} /></button><button className="ba-lb-prev" onClick={event => { event.stopPropagation(); move(-1); }} aria-label={ui.previous}><ChevronLeft size={28} /></button><motion.div key={lightbox} className="ba-lb-content" initial={{ scale: 0.92, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} onClick={event => event.stopPropagation()}>{cases[lightbox].after ? <div className="grid grid-cols-2"><img src={cases[lightbox].before} alt={cases[lightbox].beforeAlt} className="ba-lb-img" /><img src={cases[lightbox].after} alt={cases[lightbox].afterAlt} className="ba-lb-img" /></div> : <img src={cases[lightbox].before} alt={cases[lightbox].beforeAlt} className="ba-lb-img" />}<div className="ba-lb-footer"><div><strong>{cases[lightbox].title}</strong>{cases[lightbox].description && <p className="text-sm opacity-70 mt-1">{cases[lightbox].description}</p>}</div><span className="ba-lb-counter">{lightbox + 1} / {cases.length}</span></div></motion.div><button className="ba-lb-next" onClick={event => { event.stopPropagation(); move(1); }} aria-label={ui.next}><ChevronRight size={28} /></button></motion.div>}</AnimatePresence>
    <section className="section-padding bg-primary text-center"><div className="container-dental"><h2 className="text-2xl md:text-3xl font-display font-bold text-primary-foreground mb-3">{t.footerCta}</h2><p className="text-primary-foreground/70 mb-6 text-sm">{ui.final}</p><WhatsAppButton text={t.freeConsultation} variant="hero" /></div></section>
  </>;
}
