-- Intentionally empty.
-- Production and fresh environments must never create a shared demo account
-- or store a reusable password in source control. Invite named users through
-- Supabase Auth and grant the minimum role required.
